[workspace]
resolver = "3"
members = ["lib", "ratatui-world", "shader"]

[workspace.dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
glam = { version = "0.31.0" }
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git" }

# Compile build-dependencies in release mode with
# the same settings as regular dependencies.
[profile.release.build-override]
opt-level = 3
codegen-units = 16

[profile.dev.build-override]
opt-level = 3

